#!/bin/bash
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so
# it could be python, php, ruby, etc.

#  Do gulp
OLD_HOME=$HOME
export HOME=$OPENSHIFT_REPO_DIR
if [ -f "${OPENSHIFT_REPO_DIR}"/gulpfile.js ]; then
   echo "  - Running gulp build ... "
   echo
   (cd "${OPENSHIFT_REPO_DIR}"; ./node_modules/.bin/gulp build)
fi
export HOME=$OLD_HOME
